const fd = require("./field.js");
const base = "http://bgm.hisyaku.com/mmo/";

const field = [];
fd.forEach((f,i) => {
    field.push(f.name);
});

/* 敵情報
{
    name: 名前 デフォルト=null
    code: データ名 デフォルト=name値
    hp: HP補正倍率 (レベル×倍率+30=HP) デフォルト=1
    mp: 最大魔力 デフォルト=1000
    atk: 攻撃補正 デフォルト=1
    spd: 敏捷補正 デフォルト=1
    skill: [{
        name: 技名,
        per: 確率,
    } ...], デフォルト=攻撃のみ
    zokusei: 敵属性 (地、雷、水、火、草) デフォルト=無
    des: 敵説明分 デフォルト=-
    effect: [[状態異常名, レベル, 持続ターン] ...] デフォルト=[]
    field: [出現するフィールド名 ...] デフォルト=全フィールド
    exp: 経験値倍率補正 デフォルト=1
    g: ギル倍率補正 デフォルト=1
    i: [[ドロップアイテムID, 個数, 確率] ...] デフォルト=[["p", 1, 5], ["e", 1, 1]]
    hunt: [[盗めるアイテムID, 個数, 確率] ...] デフォルト=[]
    pic: 画像URL デフォルト=undefined
    rare: レアリティ (0=通常 1=レア 2=超レア) デフォルト=0
    ability: アビリティレア デフォルト=["N", "R", "SR"]
    only: 固有アビリティ名
    dif: 出現する難易度 デフォルト=["NORMAL", "HARD", "EXTREME"]
}
*/

const enemy = [
    {
        name: "yayyyy",
        code: "test",
        hp: 15,
        atk: 6.5,
        spd: 0.75,
        exp: 100,
        g: 80,
        zokusei: "地",
        des: "をぉぉぉぉぉぉ",
        field: [],
        effect: [["ダメージ上昇", 10, 9999], ["ダメージ軽減", 10, 9999], ["猛毒耐性", 1, 9999], ["即死耐性", 1, 9999]],
        pic: "393566322237374467.gif",
        ability: ["N", "R", "SR", "UR"],
        rare: 2,
    },
    {
        name: "悪魔の種",
        code: "seed",
        mp: 100,
        spd: 0.5,
        zokusei: "草",
        des: "突然変異で意志を持った植物の種だ。",
        skill: [
            { name:"攻撃", per:75 },
            { name:"ツルの鞭", per:30 },
            { name:"噛みつく", per:10 },
        ],
        field: ["草原", "沼", "毒沼", "湖", "秘境"],
        pic: "seed.png",
    },
    {
        name: "アナコンダ",
        code: "anaconda",
        skill: [
            { name:"攻撃", per:75 },
            { name:"噛みつく", per:30 },
            { name:"毒牙", per:30 },
        ],
        effect: [["毒耐性", 5, 9999]],
        field: ["草原", "洞窟", "沼", "遺跡"],
        pic: "anaconda.png",
    },
    {
        name: "キャタピラー",
        code: "imomushi",
        atk: 0.5,
        hp: 1.6,
        zokusei: "草",
        skill: [
            { name:"攻撃", per:75 },
        ],
        field: ["草原"],
        pic: "caterpillar.png",
    },
    {
        name: "サソリ",
        code: "sasori",
        mp: 500,
        zokusei: "地",
        skill: [
            { name:"攻撃", per:50 },
            { name:"毒針", per:50 },
        ],
        field: ["草原", "峡谷", "洞窟", "沼", "毒沼"],
        pic: "scorpion.png",
    },
    {
        name: "マタンゴ",
        code: "matango",
        mp: 500,
        zokusei: "草",
        skill: [
            { name:"攻撃", per:75 },
            { name:"毒の粉", per:30 },  
        ],
        field: ["草原", "峡谷", "火山", "沼", "毒沼", "秘境", "氷山", "湖", "遺跡", "竜洞"],
        pic: "kinoko.png",
        effect: [["再生", 1, 9999]],
    },
    {
        name: "モス",
        code: "moss",
        hp: 1.25,
        zokusei: "草",
        skill: [
            { name:"攻撃", per:45 },
            { name:"ツルの鞭", per:75 },  
        ],
        field: ["草原", "沼", "秘境", "遺跡"],
        pic: "moss.png",
    },
    {
        name: "チェリー",
        code: "cherry",
        hp: 0.8,
        zokusei: "草",
        skill: [
            { name:"攻撃", per:75 },
            { name:"ツルの鞭", per:45 },
        ],
        field: ["草原", "氷原", "秘境", "氷山"],
        pic: "cherry.png",
    },
    {
        name: "グラス",
        code: "grass",
        hp: 1.44,
        zokusei: "草",
        skill: [
            { name:"何もしない", per:55 },
        ],
        field: ["草原", "湖"],
        pic: "grass.png",
    },
    {
        name: "ソーン",
        code: "thorn",
        hp: 0.8,
        atk: 1.66,
        zokusei: "草",
        skill: [
            { name:"何もしない", per:45 },
            { name:"攻撃", per:35 },
            { name:"針飛ばし", per:25 },
            { name:"ツルの鞭", per:25 },
            { name:"毒針", per:15 },
        ],
        field: ["草原", "洞窟", "峡谷", "沼"],
        pic: "thorn.png",
    },
    {
        name: "コウモリ",
        code: "bat",
        spd: 3,
        skill: [
            { name:"攻撃", per:60 },
            { name:"噛みつく", per:60 },
            { name:"毒牙", per:30 },
            { name:"しっぽ", per:30 },
        ],
        field: ["洞窟", "峡谷", "火山", "沼", "湖", "毒沼", "氷山", "遺跡"],
        pic: "bat.png",
    },
    {
        name: "マイマイ",
        code: "maimai",
        hp: 1.2,
        zokusei: "水",
        skill: [
            { name:"攻撃", per:55 },
            { name:"殻で挟む", per:35 },
            { name:"水鉄砲", per:40 },
        ],
        field: ["洞窟", "氷原", "沼", "湖"],
        effect: [["ダメージ軽減", 5, 9999]],
        pic: "maimai.png",
    },
    {
        name: "ヤドカリ",
        code: "yadokari",
        hp: 1.2,
        zokusei: "水",
        skill: [
            { name:"攻撃", per:55 },
            { name:"殻で挟む", per:35 },
            { name:"水鉄砲", per:40 },
        ],
        field: ["洞窟", "氷原", "沼", "毒沼", "湖", "遺跡"],
        effect: [["ダメージ軽減", 1, 9999], ["再生", 1, 9999]],
        pic: "yadokari.png",
    },
    {
        name: "アイシクル",
        code: "icicle",
        hp: 0.9,
        zokusei: "氷",
        skill: [
            { name:"攻撃", per:45 },
            { name:"頭突き", per:55 },
            { name:"フローズン", per:55 },
            { name:"吹雪", per:20 },
        ],
        field: ["氷原", "氷山"],
        pic: "icicle.png",
    },
    {
        name: "スノーマン",
        code: "snowman",
        hp: 1.2,
        exp: 2,
        g: 2,
        zokusei: "氷",
        skill: [
            { name:"何もしない", per:30 },
            { name:"攻撃", per:40 },
            { name:"雪玉", per:50 },
            { name:"石入りの雪玉", per:20 },
        ],
        field: ["氷原", "氷山"],
        pic: "snowman.png",
    },
    {
        name: "ペンギン",
        code: "penguin",
        atk: 0.6,
        hp: 1.2,
        zokusei: "氷",
        skill: [
            { name:"攻撃", per:60 },
            { name:"雪玉", per:35 },
            { name:"引っかく", per:30 },
            { name:"ブレイブ", per:25 },
        ],
        field: ["氷原", "氷山"],
        pic: "penguin.png",
    },
    {
        name: "マッドハンド",
        code: "mudhand",
        atk: 1.2,
        hp: 1.2,
        zokusei: "地",
        skill: [
            { name:"攻撃", per:45 },
            { name:"引っかく", per:30 },
            { name:"泥玉", per:55 },
        ],
        field: ["峡谷", "沼", "秘境", "遺跡"],
        pic: "hand.png",
    },
    {
        name: "ネズミ",
        code: "rat",
        hp: 1.2,
        atk: 0.75,
        zokusei: "地",
        skill: [
            { name:"何もしない", per:25 },
            { name:"引っかく", per:50 },
            { name:"泥玉", per:30 },
        ],
        field: ["洞窟", "峡谷", "秘境", "氷山", "遺跡", "竜洞"],
        pic: "mouse.png",
    },
    {
        name: "ノミ",
        code: "flea",
        hp: 0.7,
        atk: 0.7,
        zokusei: "地",
        g: 0.5,
        skill: [
            { name:"攻撃", per:65 },
            { name:"噛みつく", per:40 },
        ],
        field: ["洞窟", "峡谷", "火山", "沼", "毒沼", "氷山"],
        pic: "flea.png",
    },
    {
        name: "踊る金貨",
        code: "coin",
        hp: 0.5,
        zokusei: "地",
        exp: 0.5,
        g: 50,
        skill: [
            { name:"何もしない", per:50 },
            { name:"攻撃", per:50 },
        ],
        field: ["峡谷", "秘境"],
        pic: "coin.png",
        rare: 3,
    },
    {
        name: "フォグ",
        code: "fog",
        hp: 0.8,
        atk: 1.25,
        zokusei: "地",
        skill: [
            { name:"攻撃", per:40 },
            { name:"火の粉", per:30 },
            { name:"粉塵", per:50 },
        ],
        field: ["火山", "毒沼", "秘境", "氷山", "地獄", "竜洞"],
        pic: "fog.png",
    },
    {
        name: "ボム",
        code: "bomb",
        hp: 2,
        mp: 3000,
        zokusei: "火",
        skill: [
            { name:"何もしない", per:65 },
            { name:"頭突き", per:35 },
            { name:"粉塵", per:35 },
            { name:"自爆", per:8 },
        ],
        field: ["火山", "毒沼", "地獄", "遺跡"],
        pic: "bomb.png",
    },
    {
        name: "サラマンダー",
        code: "salamander",
        hp: 0.85,
        mp: 2500,
        zokusei: "火",
        skill: [
            { name:"攻撃", per:30 },
            { name:"引っかく", per:50 },
            { name:"粉塵", per:50 },
            { name:"フレア", per:15 },
        ],
        field: ["火山", "地獄", "竜洞"],
        pic: "salamander.png",
        effect: [["ダメージ上昇", 1, 9999]],
    },
    {
        name: "タンク",
        code: "tank",
        zokusei: "地",
        hp: 1.2,
        mp: 750,
        skill: [
            { name:"攻撃", per:75 },
            { name:"大砲", per:35 },
            { name:"粉塵", per:45 },
        ],
        field: ["火山", "遺跡"],
        pic: "tank.png",
        effect: [["ダメージ軽減", 3, 9999]],
    },
    {
        name: "ヘルハウンド",
        code: "hellhound",
        zokusei: "火",
        hp: 1.33,
        atk: 1.22,
        skill: [
            { name:"引っかく", per:45 },
            { name:"炎牙", per:35 },
            { name:"火の粉", per:35 },
            { name:"粉塵", per:55 },
        ],
        field: ["火山", "地獄"],
        pic: "hellhound.png",
    },
    {
        name: "ヒドラ",
        code: "hydra",
        zokusei: "火",
        hp: 1.22,
        atk: 1.44,
        exp: 5,
        skill: [
            { name:"攻撃", per:55 },
            { name:"猛毒牙", per:35 },
            { name:"炎牙", per:35 },
            { name:"粉塵", per:55 },
            { name:"フレア", per:25 },
        ],
        field: ["火山", "秘境", "地獄", "竜洞"],
        pic: "hydra.png",
    },
    {
        name: "ウロボロス",
        code: "uroboros",
        skill: [
            { name:"攻撃", per:45 },
            { name:"噛みつく", per:35 },
            { name:"フレア", per:15 },
            { name:"毒牙", per:25 },
            { name:"猛毒牙", per:25 },
        ],
        field: ["峡谷", "火山", "沼", "毒沼"],
        pic: "uroboros.png",
    },
    {
        name: "エッグ",
        code: "egg",
        zokusei: "闇",
        hp: 2,
        spd: 10,
        exp: 20,
        g: 10,
        skill: [
            { name:"頭突き", per:35 },
            { name:"引っかく", per:55 },
            { name:"プロテ", per:25 },
            { name:"粉塵", per:30 },
            { name:"あやかしの呪文", per:5 },
        ],
        field: ["火山", "遺跡", "竜洞"],
        pic: "egg.png",
        rare: 3,
    },
    {
        name: "ゴースト",
        code: "ghost",
        zokusei: "闇",
        skill: [
            { name:"攻撃", per:75 },
            { name:"儚い闇", per:35 },
            { name:"あやかしの呪文", per:5 },
        ],
        field: ["冥界", "地獄"],
        pic: "ghost_white.png",
    },
    {
        name: "ポルターガイスト",
        code: "polter",
        hp: 1.2,
        zokusei: "闇",
        skill: [
            { name:"攻撃", per:45 },
            { name:"椅子で打つ", per:55 },
            { name:"あやかしの呪文", per:5 },
        ],
        field: ["冥界", "遺跡"],
        pic: "poltergeist.png",
    },
    {
        name: "ファントム",
        code: "phantom",
        hp: 1.2,
        atk: 1.3,
        zokusei: "闇",
        skill: [
            { name:"攻撃", per: 70 },
            { name:"儚い闇", per:50 },
            { name:"常闇", per: 10 },
            { name:"あやかしの呪文", per:5 },
        ],
        field: ["冥界", "地獄"],
        pic: "phantom.png",
    },
    {
        name: "スピリット",
        code: "spirit",
        hp: 1.33,
        zokusei: "闇",
        skill: [
            { name:"攻撃", per:45 },
            { name:"儚い闇", per:55 },
            { name:"鬼火", per:15 },
            { name:"何もしない", per:5 },
        ],
        field: ["冥界"],
        effect: [["透明化", 1, 9999]],
        pic: "spirit.png",
    },
    {
        name: "シャドウ",
        code: "shadow",
        hp: 1.2,
        zokusei: "闇",
        skill: [
            { name:"攻撃", per:55 },
            { name:"儚い闇", per:35 },
            { name:"常闇", per:15 },
        ],
        field: ["秘境", "氷山", "地獄"],
        pic: "shadow.png",
    },
    {
        name: "ガスト",
        code: "ghast",
        hp: 0.9,
        exp: 1.2,
        skill: [
            { name:"攻撃", per:75 },
            { name:"火の粉", per:35 },
            { name:"電流", per:35 },
            { name:"毒の粉", per:35 },
            { name:"あやかしの呪文", per:5 },
        ],
        field: ["火山", "毒沼", "秘境", "氷山", "湖", "地獄", "遺跡"],
        pic: "ghast.png"
    },
    {
        name: "カロン",
        code: "charon",
        hp: 1.1,
        zokusei: "闇",
        skill: [
            { name:"攻撃", per:35 },
            { name:"頭突き", per:25 },
            { name:"フレア", per:35 },
            { name:"ザップ", per:25 },
            { name:"アクア", per:15 },
        ],
        field: ["火山", "毒沼", "秘境", "地獄"],
        effect: [["ダメージ軽減", 1, 9999]],
        pic: "charon.png",
    },
    {
        name: "プラズマ",
        code: "plasma",
        zokusei: "雷",
        hp: 1.5,
        skill: [
            { name:"攻撃", per:45 },
            { name:"電流", per:80 },
            { name:"ザップ", per:25 },
        ],
        field: ["氷山", "天界", "湖", "地獄", "遺跡"],
        pic: "el_plasma.png",
    },
    {
        name: "クレセント",
        code: "crescent",
        zokusei: "光",
        skill: [
            { name:"攻撃", per:55 },
            { name:"電流", per:75 },
            { name:"淡い光", per:45 },
            { name:"極光", per:10 },
        ],
        pic: "crescent.png",
        field: ["天界"],
        effect: [["ダメージ軽減", 2, 9999]],
    },
    {
        name: "レイン",
        code: "rain",
        hp: 30,
        atk: 0.33,
        zokusei: "水",
        skill: [
            { name:"何もしない", per:30 },
            { name:"攻撃", per:75 },
            { name:"プロテ", per:45 },
            { name:"レイン", per:25 },
            { name:"アクア", per:25 },
        ],
        pic: "el_rain.png",
        field: ["湖", "天界"],
        effect: [["落下", 2, 6]],
    },
    {
        name: "シルフ",
        code: "sylph",
        spd: 5,
        zokusei: "光",
        skill: [
            { name:"攻撃", per:25 },
            { name:"淡い光", per:35 },
            { name:"プロテ", per:25 },
        ],
        field: ["天界"],
        pic: "shylph.png",
    },
    {
        name: "ウィルオウィスプ",
        code: "wisp",
        hp: 0.8,
        atk: 1.333,
        zokusei: "火",
        skill: [
            { name:"何もしない", per:45 },
            { name:"攻撃", per:35 },
            { name:"鬼火", per:55 },
            { name:"フレア", per:15 },
        ],
        field: ["天界", "地獄", "遺跡"],
        pic: "wisp.png",
    },
    {
        name: "てるてる坊主",
        code: "teru",
        hp: 1.75,
        atk: 0.666,
        zokusei: "闇",
        skill: [
            { name:"何もしない", per:25 },
            { name:"攻撃", per:25 },
            { name:"メルトン", per:50 },
            { name:"レイン", per:25 },
            { name:"あやかしの呪文", per:5 },
        ],
        field: ["天界"],
        pic: "tt-boy.png",
    },
    {
        name: "プロミネンス",
        code: "prominence",
        atk: 1.33,
        zokusei: "火",
        skill: [
            { name:"火の粉", per:75 },
            { name:"鬼火", per:55 },
            { name:"フレア", per:35 },
            { name:"青い炎", per:15 },
            { name:"スーパーノヴァ", per:5 },
        ],
        field: ["地獄"],
        pic: "prominence.png",
    },
    {
        name: "ラーヴァ",
        code: "larva",
        zokusei: "闇",
        atk: 0.85,
        skill: [
            { name:"何もしない", per: 25 },
            { name:"攻撃", per: 55 },
            { name:"ブラックホール", per: 15 },
        ],
        field: ["遺跡"],
        effect: [["ダメージ軽減", 2, 9999]],
        pic: "larva.png",
    },
    {
        name: "アイアンメイデン",
        code: "maiden",
        zokusei: "無",
        atk: 1.222,
        mp: 777,
        skill: [
            { name:"何もしない", per:25 },
            { name:"針飛ばし", per: 65 },
            { name:"ブラックホール", per:10 },
            { name:"体を閉じる", per:5 },
        ],
        field: ["遺跡"],
        pic: "iron_maiden.png",
    },
    {
        name: "ナイト",
        code: "knight",
        zokusei: "闇",
        hp: 0.8,
        atk: 1.44,
        mp: 444,
        skill: [
            { name:"攻撃", per:65 },
            { name:"切り裂く", per:45 },
            { name:"常闇", per:15 },
            { name:"シグルイ", per:5 },
        ],
        field: ["遺跡"],
        effect: [["ダメージ軽減", 4, 9999]],
        pic: "knight.png",
    },
    {
        name: "朧車",
        code: "oboro",
        zokusei: "火",
        hp: 1.333,
        atk: 0.666,
        mp: 4444,
        skill: [
            { name:"鬼火", per:60 },
            { name:"火の粉", per:50 },
            { name:"フレア", per:40 },
            { name:"青い炎", per:30 },
            { name:"ヘルファイア", per:20 },
        ],
        field: ["冥界", "遺跡"],
        pic: "wheel.png",
    },
    {
        name: "キラーマシン",
        code: "killer",
        mp: 1000,
        skill: [
            { name:"攻撃", per:50 },
            { name:"矢", per:65 },
            { name:"切り裂く", per:15 },
        ],
        repeat: 2,
        field: ["遺跡"],
        effect: [["ダメージ軽減", 1, 9999], ["ダメージ上昇", 3, 9999]],
        pic: "k-machine.png",
    },
    {
        name: "バハムート",
        code: "bahamut",
        hp: 3,
        mp: 10000,
        atk: 1.33,
        spd: 0.66,
        exp: 10,
        zokusei: "火",
        skill: [
            { name:"引っかく", per:60 },
            { name:"頭突き", per:25 },
            { name:"青い炎", per:45 },
            { name:"メガフレア", per:10 },
        ],
        field: ["竜洞"],
        pic: "bahamut.png",
    },
    {
        name: "コアトル",
        code: "coatl",
        hp: 2.5,
        atk: 0.66,
        spd: 4.4,
        exp: 10,
        skill: [
            { name:"引っかく", per:55 },
            { name:"頭突き", per:25 },
            { name:"黒雷", per:35 },
            { name:"レイン", per:35 },
            { name:"フレア", per:35 },
        ],
        effect: [["ダメージ軽減", 18, 4], ["ダメージ上昇", 18, 4]],
        field: ["竜洞"],
        pic: "coatl.png",
    },
    {
        name: "双頭龍",
        code: "twins",
        hp: 6.5,
        atk: 1.2,
        spd: 0.55,
        exp: 10,
        zokusei: "地",
        skill: [
            { name:"攻撃", per:35 },
            { name:"頭突き", per:15 },
            { name:"" },
        ],
        repeat: 2,
        field: ["竜洞"],
        effect: [["被ダメージ上昇", 3, 9999]],
        pic: "dragon_w.png",
    },
    {
        name: "恐竜",
        code: "dinosaur",
        hp: 2.2,
        atk: 2.2,
        spd: 2.2,
        exp: 10,
        zokusei: "火",
        skill: [
            { name:"攻撃", per:35 },
            { name:"引っかく", per:65 },
            { name:"フレア", per:45 },
            { name:"クエイク", per:25 },
        ],
        field: ["竜洞"],
        pic: "dinosaur.png",
    },
    {
        name: "スカルドラゴン",
        code: "skull",
        hp: 3.6,
        atk: 6.3,
        spd: 1.2,
        exp: 10,
        mp: 6666,
        zokusei: "虚",
        skill: [
            { name:"攻撃", per:25 },
            { name:"常闇", per:40 },
            { name:"極光", per:40 },
            { name:"シグルイ", per:50 },
        ],
        effect: [["ダメージ低下", 8, 3]],
        field: ["竜洞"],
        pic: "dragon_s.png", 
    },
    {
        name: "ドラゴンゾンビ",
        code: "zombie",
        hp: 4.4,
        atk: 4.444,
        spd: 0.444,
        exp: 10,
        zokusei: "地",
        skill: [
            { name:"引っかく", per:45 },
            { name:"メルトン", per:55 },
            { name:"フレア", per:25 },
            { name:"ザップ", per:25 },
            { name:"アクア", per:25 },
            { name:"シグルイ", per:5 },
        ],
        field: ["竜洞"],
        effect: [["被ダメージ上昇", 5, 9999]],
        pic: "dragon_z.png",
    },
    {
        name: "不滅の種",
        code: "u-seed",
        hp: 5.2,
        exp: 20,
        zokusei: "草",
        skill: [
            { name:"攻撃", per:85 },
            { name:"ツルの鞭", per:20 },
            { name:"噛みつく", per:20 },
        ],
        field: ["草原", "沼", "毒沼", "秘境"],
        effect: [["再生", 1, 9999]],
        pic: "seed.png",
        rare:1,
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "草",
        code: "s-grass",
        hp: 7.77,
        atk: 1.6,
        exp: 20,
        zokusei: "草",
        skill: [
            { name:"何もしない", per:35 },
            { name:"ツルの鞭", per:55 },
            { name:"ハードプラント", per:8 },
        ],
        rare: 1,
        field: ["草原", "湖", "沼", "遺跡", "秘境"],
        effect: [["再生", 3, 9999], ["被ダメージ上昇", 2, 9999]],
        pic: "grass.png",
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "神速のサソリ",
        code: "s-sasori",
        mp: 500,
        hp: 1.22,
        atk: 1.55,
        spd: 5.5,
        exp: 20,
        zokusei: "地",
        skill: [
            { name:"攻撃", per:70 },
            { name:"毒針", per:20 },
        ],
        field: ["峡谷", "洞窟", "沼", "毒沼"],
        pic: "scorpion.png",
        rare: 1,
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "貧弱なモス",
        code: "h-moss",
        mp: 10000,
        hp: 1.66,
        atk: 1.8,
        exp: 20,
        zokusei: "草",
        skill: [
            { name:"攻撃", per:20 },
            { name:"ツルの鞭", per:50 },
            { name:"頭突き", per:50 },
        ],
        field: ["草原", "沼", "秘境", "遺跡"],
        pic: "moss.png",
        rare:1,
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "夜桜",
        code: "y-cherry",
        hp: 5.5,
        mp: 2000,
        atk: 0.55,
        exp: 20,
        g: 20,
        zokusei: "草",
        skill: [
            { name:"攻撃", per:30 },
            { name:"ツルの鞭", per:30 },
            { name:"プロテ", per:40 },
            { name:"ブレイブ", per:40 },
        ],
        field: ["秘境"],
        pic: "cherry.png",
        rare:1,
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "ダイアル",
        code: "d-uroboros",
        hp: 3.777,
        atk: 1.111,
        spd: 2.55,
        mp: 1341,
        atk: 1.25,
        exp: 20,
        zokusei: "闇",
        skill: [
            { name:"タイムストッパー", per:18 },
            { name:"噛みつく", per:35 },
            { name:"猛毒牙", per:45 },
            { name:"フレア", per:55 },
        ],
        rare: 1,
        field: ["毒沼", "峡谷", "秘境"],
        effect: [["ダメージ軽減", 3, 9999]],
        pic: "uroboros.png",
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "スフィア・オブ・ヘル",
        code: "soh-cube",
        hp: 5.5,
        mp: 3000,
        atk: 0.33,
        exp: 20,
        g: 20,
        zokusei: "火",
        skill: [
            { name:"鬼火", per:25 },
            { name:"スペース", per:25 },
            { name:"ブラックホール", per:25 },
            { name:"絶望の歌", per:25 },
            { name:"あやかしの呪文", per:25 },
        ],
        field: ["地獄"],
        pic: "cube.png",
        rare: 1,
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "イエティ",
        code: "yeti",
        hp: 1.33,
        atk: 1.96,
        exp: 20,
        zokusei: "氷",
        skill: [
            { name:"攻撃", per:30 },
            { name:"頭突き", per:40 },
            { name:"石入りの雪玉", per:60 },
            { name:"吹雪", per:60 },
        ],
        field: ["氷原", "氷山"],
        pic: "yeti.png",
        rare:1,
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "ウェル",
        code: "well",
        hp: 4,
        atk: 1.66,
        exp: 20,
        zokusei: "水",
        skill: [
            { name:"攻撃", per:20 },
            { name:"引っかく", per:20 },
            { name:"水鉄砲", per:65 },
            { name:"アクア", per:35 },
            { name:"絶望の歌", per:15 },
        ],
        field: ["沼", "毒沼", "秘境", "氷山", "遺跡"],
        pic: "well.png",
        rare:1,
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "デルタ1st",
        code: "delta",
        hp: 1,
        atk: 1.111,
        mp: 1500,
        exp: 0,
        zokusei: "雷",
        skill: [
            { name:"攻撃", per:40 },
            { name:"矢", per:70 },
            { name:"大砲", per:30 },
            { name:"電流", per:20 },
        ],
        field: ["遺跡"],
        effect: [["ダメージ軽減", 1, 9999]],
        pic: "delta.png",
        rare: 1,
        next: {
            code: "delta2nd",
            msg: "DELTA 2nd-Form Loading...",
        },
    },
    {
        name: "デルタ2nd",
        code: "delta2nd",
        hp: 2.5,
        atk: 1.333,
        exp: 40,
        mp: 3000,
        zokusei: "雷",
        skill: [
            { name:"矢", per:25 },
            { name:"大砲", per:55 },
            { name:"クエイク", per:30 },
            { name:"ザップ", per:25 },
            { name:"ボルテガ", per:5 },
        ],
        field: [],
        effect: [["ダメージ軽減", 3, 9999]],
        pic: "delta.png",
        rare: 1,
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "ミミック",
        code: "mimic",
        mp: 50000,
        hp: 0.75,
        g: 200,
        zokusei: "闇",
        skill: [
            { name:"何もしない", per:22 },
            { name:"噛みつく", per:66 },
            { name:"猛毒牙", per:55 },
            { name:"絶望の歌", per:44 },
            { name:"あやかしの呪文", per:22 },
        ],
        pic: "pandora.png",
        i: [["c", 1, 5]],
        effect: [["ダメージ軽減", 10, 9999], ["猛毒耐性", 1, 9999]],
        rare:1,
        ability: ["N", "R", "SR", "UR"],
        only: "孔明の罠",
    },
    {
        name: "魔鏡",
        code: "mirror",
        hp: 0.2,
        atk: 0.65,
        mp: 44444,
        spd: 0.1,
        exp: 0.8,
        g: 0.8,
        zokusei: "闇",
        skill: [
            { name:"何もしない", per:30 },
            { name:"儚い闇", per:60 },
            { name:"吸い込み", per:30 },
        ],
        field: ["毒沼", "冥界", "遺跡"],
        pic: "mirror.png",
        rare: 1,
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "キケロ",
        code: "cicero",
        hp: 3,
        mp: 10000,
        spd: 3,
        exp: 85,
        g: 50,
        i: [["p", 20, 100], ["t", 20, 100], ["e", 5, 100], ["c", 1, 5]],
        zokusei: "地",
        skill: [
            { name:"攻撃", per:30 },
            { name:"しっぽ", per:50 },
            { name:"頭突き", per:50 },
            { name:"あやかしの呪文", per:5 },
        ],
        pic: "cicero.png",
        rare: 2,
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "デュラハン",
        code: "dullahan",
        hp: 2,
        atk: 5.4,
        spd: 0.8,
        exp: 100,
        g: 80,
        i: [["p", 20, 100], ["t", 20, 100], ["e", 5, 100], ["c", 1, 5]],
        zokusei: "闇",
        skill: [
            { name:"攻撃", per:50 },
            { name:"槍突き", per:50 },
            { name:"常闇", per:30 },
            { name:"あやかしの呪文", per:20 },
        ],
        pic: "dullahan.png",
        rare: 2,
        field: ["峡谷", "火山", "秘境"],
        effect: [["ダメージ上昇", 5, 9999]],
        ability: ["N", "R", "SR", "UR"],
        only: "最強の槍",
    },
    {
        name: "カースト",
        code: "curst",
        pic: "death_bk.png",
        hp: 1.444,
        atk: 3.6,
        spd: 2.4,
        exp: 100,
        g: 80,
        i: [["p", 20, 100], ["t", 20, 100], ["e", 5, 100], ["c", 1, 5]],
        zokusei: "闇",
        skill: [
            { name:"切り裂く", per:65 },
            { name:"大鎌", per:35 },
            { name:"常闇", per:15 },
            { name:"デッドワールド", per:5 },
        ],
        rare: 2,
        field: ["沼", "冥界"],
    },
    {
        name: "デス",
        code: "death",
        hp: 1.666,
        atk: 2.5,
        spd: 3.2,
        exp: 100,
        g: 80,
        i: [["p", 20, 100], ["t", 20, 100], ["e", 5, 100], ["c", 1, 5]],
        zokusei: "闇",
        skill: [
            { name:"攻撃", per:70 },
            { name:"黒雷", per:30 },
            { name:"常闇", per:30 },
            { name:"大鎌", per:30 },
        ],
        pic: "death.png",
        rare: 2,
        field: ["毒沼", "地獄"],
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "白虎",
        code: "byakko",
        hp: 7.5,
        atk: 0.666,
        spd: 2.5,
        exp: 100,
        g: 80,
        i: [["p", 20, 100], ["t", 20, 100], ["e", 5, 100], ["c", 1, 5]],
        zokusei: "光",
        skill: [
            { name:"噛みつく", per:50 },
            { name:"しっぽ", per:30 },
            { name:"猛毒牙", per:30 },
            { name:"淡い光", per:30 },
        ],
        pic: "byakko.png",
        rare:2,
        effect: [["再生", 3, 9999]],
        field: ["草原", "洞窟", "氷原"],
    },
    {
        name: "極楽鳥",
        code: "condor",
        hp: 50,
        atk: 0.5,
        spd: 8,
        exp: 100,
        g: 80,
        i: [["p", 20, 100], ["t", 20, 100], ["e", 5, 100], ["c", 1, 5]],
        zokusei: "光",
        skill: [
            { name:"攻撃", per:50 },
            { name:"しっぽ", per:45 },
            { name:"絶望の歌", per:15 },
            { name:"極光", per:30 },
            { name:"常闇", per:30 },
        ],
        pic: "condor.png",
        rare: 2,
        field: ["湖", "氷山", "天界"],
        effect: [["落下", 2, 15]],
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "青龍",
        code: "seiryu",
        hp: 4.7,
        atk: 0.5,
        spd: 2.2,
        exp: 100,
        g: 80,
        zokusei: "水",
        skill: [
            { name:"切り裂く", per:70 },
            { name:"メガフレア", per:25 },
            { name:"ボルテガ", per:25 },
            { name:"ウェルテクス", per:25 },
            { name:"グランドフォース", per:25 },
        ],
        rare: 2,
        field: ["遺跡", "竜洞"],
        i: [["p", 20, 100], ["t", 20, 100], ["e", 5, 100], ["c", 1, 5]],
        effect: [["ダメージ軽減", 18, 4], ["ダメージ上昇", 18, 4]],
        pic: "seiryuu.png",
        ability: ["N", "R", "SR", "UR"],
    },
    {
        name: "金虎",
        code: "gold-tiger",
        hp: 13.333,
        atk: 0.75,
        spd: 3.6,
        exp: 100,
        g: 1500,
        zokusei: "光",
        skill: [
            { name:"切り裂く", per:55 },
            { name:"淡い光", per:45 },
            { name:"ライトニング", per:35 },
            { name:"猛毒牙", per:25 },
        ],
        rare: 4,
        effect: [["石化", 1, 3], ["再生", 6, 9999], ["ダメージ軽減", 3, 9999]],
        i: [["p", 30, 100], ["t", 30, 100], ["e", 10, 100], ["c", 3, 100]],
        field: ["遺跡", "秘境"],
        pic: "byakko_y.png",
    },
    {
        name: "Nightmare",
        code: "nightmare",
        hp: 104,
        atk: 7.4,
        spd: 3.7,
        exp: 22.222,
        g: 22.222,
        mp: 124425,
        repeat: 2,
        zokusei: "虚",
        skill: [
            { name:"スペース", per:15 },
            { name:"ノーライフ", per:25 },
            { name:"-273度", per:35 },
            { name:"病夢", per:40 },
            { name:"アンディファインド", per:45 },
        ],
        field: [],
        effect: [["天邪鬼", 1, 9999], ["ダメージ軽減", 10, 9999], ["遮光", 1, 9999], ["浮遊", 1, 9999]],
        pic: "nightmare.png",
        ability: ["N", "R", "SR", "UR"],
        noescape: {
            msg: `「私は強きものによって移り変わる。貴様らを葬るためにな...」`,  
        },
    },
    {
        name: "Nightmare",
        code: "omni-nightmare",
        hp: 104,
        atk: 7.4,
        spd: 3.7,
        exp: 22.222,
        g: 22.222,
        mp: 124425,
        repeat: 2,
        zokusei: "虚",
        skill: [
            { name:"スペース", per:15 },
            { name:"ノーライフ", per:25 },
            { name:"-273度", per:35 },
            { name:"病夢", per:40 },
            { name:"アンディファインド", per:45 },
        ],
        field: ["永遠悪夢"],
        effect: [["天邪鬼", 1, 9999], ["ダメージ軽減", 10, 9999], ["遮光", 1, 9999], ["浮遊", 1, 9999]],
        pic: "nightmare.png",
        ability: ["N", "R", "SR", "UR"],
        noescape: {
            msg: `「永遠の悪夢、楽しんでゆくが良い...」`,  
        },
    },
    {
        name: "Protomare",
        code: "daydream",
        hp: 47.5,
        atk: 2.7,
        spd: 8.4,
        mp: 114514,
        exp: 22.222,
        g: 22.222,
        zokusei: "虚",
        skill: [
            { name:"スペース", per:15 },
            { name:"タイムストッパー", per:25 },
            { name:"エンプティセット", per:35 },
            { name:"病夢", per: 40 },
            { name:"アンディファインド", per:45 },
        ],
        field: [],
        effect: [["完全耐性", 1, 9999], ["魔法障壁", 1, 9999], ["半石化", 2, 9999], ["浮遊", 1, 9999]],
        pic: "nightmare_w.png",
        ability: ["N", "R", "SR", "UR"],
        noescape: {
            msg: "「...」",
        },
    },
];

enemy.forEach((e,i) => {
    if(!e.name) e.name="null";
    if(!e.code) e.code=e.name;
    if(!e.hp) e.hp=1;
    if(!e.mp) e.mp=1000;
    if(!e.atk) e.atk=1;
    if(!e.spd) e.spd=1;
    if(!e.skill) e.skill=[{ name:"攻撃", per:100 }];
    if(!e.zokusei) e.zokusei="無";
    if(!e.des) e.des="-";
    if(!e.effect) e.effect=[];
    if(!e.exp) e.exp=1;
    if(!e.g) e.g=1;
    if(!e.field) e.field=field;
    if(!e.i) e.i=[["p", 1, 5], ["t", 1, 3], ["e", 1, 1]];
    if(!e.rare) e.rare=0;
    if(!e.ability) e.ability=["N", "R", "SR"];
    if(!e.repeat) e.repeat=1;
    if(!e.mode) e.mode=["NORMAL"];
    
    e.pic = base + e.pic;
    enemy[i] = e;
});

module.exports = enemy;